const UPDATE_CYCLE = 'UPDATE_CYCLE';
const UPDATE_MASK_CYCLE = 'UPDATE_MASK_CYCLE';
const UPDATE_MASK_ANIMATION = 'UPDATE_MASK_ANIMATION';
const UPDATE_LOGIN_ANIMATION = 'UPDATE_LOGIN_ANIMATION';
export default {
     UPDATE_CYCLE,
     UPDATE_MASK_CYCLE,
     UPDATE_LOGIN_ANIMATION,
     UPDATE_MASK_ANIMATION
    };